### ISSUE TITLE
Design shrine screen

### ISSUE THREAD

**Issue by swenmeeuwes** [swenmeeuwes/GetOffMe#74]

**Comment by kevin2106** [comment]
- [x] Vial of stealthy score
- [x] Vial of  hard score
- [x] Vial of magic score
- [x] Vial of fast score
- [x] Vial of tough score

**Comment by kevin2106** [comment]
- [x] Background for vials
- [x] Arrow left and right

**Comment by swenmeeuwes** [comment]
- [ ] Shrine button in menu
- [ ] Shrine shelf for the potions
